# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18d1ZdRXr5bRtaaYnAyLghZvzFf3xjw57
"""

import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

def funcion(x):
    return (3*(x**5))+(5*(x**4))-(x**3)

x = np.linspace(-30,30,100)
y = funcion(x)

plt.plot(x,y)
plt.axhline(y=0,color='r')

def derivada(f,x,h=1e-6):
     return (f(x+h)-f(x-h))/(2*h)



def newton(f,df,xn,itmax=1000,precision=1e-5):
    
    error = 1
    it=0
    
    while error > precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(f,xn)
            error = np.abs(f(xn)/df(f,xn))
            
        except ZeroDivisionError:
            print('Division por cero')
            
        xn = xn1
        it += 1
        
    print('raiz:', xn,it)
    
    if it == itmax:
        return False
    else:
        return xn

root = GetNewtonMethod(funcion,derivada,1)

def GetAllRoots(x,tolerancia=8):
    
    Roots = np.array([])
    
    for i in x:
        root = newton(funcion,derivada,i)
        
        if root != False:
            
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
    
    return Roots

xtrial = np.linspace(-10,10,3)
Roots = GetAllRoots(xtrial)